#
# This file can be used for overriding ENV variables.
#
services:
  web:
    environment:
      - BROWSERTEST_OUTPUT_DIRECTORY=/var/www/html/web/sites/simpletest/browser_output
      - BROWSERTEST_OUTPUT_BASE_URL=${DDEV_PRIMARY_URL}
      - SIMPLETEST_DB=sqlite://tmp/sites/simpletest/db.sqlite
