# This file comes from https://github.com/drud/ddev-selenium-standalone-chrome.
#
version: '3.6'
services:
  selenium-chrome:
    image: seleniarm/standalone-chromium:4.1.4-20220429
    container_name: ddev-${DDEV_SITENAME}-selenium-chrome
    expose:
      #      The internal noVNC port, which operates over HTTP so it can be exposed
      #      through the router.
      - 7900
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTPS_EXPOSE=7900:7900
      - HTTP_EXPOSE=7910:7900
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
      #ports:
      # VNC access for a traditional VNC client like macOS "Screen Sharing".
      # - "5900:5900"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"

  web:
    links:
      - selenium-chrome
    environment:
      SYMFONY_DEPRECATIONS_HELPER: weak
      # Simpletest
      SIMPLETEST_DB_MYSQL: &simpletest_db_mysql mysql://db:db@db:3306/db
      SIMPLETEST_DB_SQLITE: &simpletest_db_sqlite sqlite://localhost//dev/shm/test.sqlite
      SIMPLETEST_DB: *simpletest_db_sqlite
      SIMPLETEST_BASE_URL: &base_url http://${DDEV_HOSTNAME}
      MINK_DRIVER_ARGS_WEBDRIVER:  &mink_driver_args '["chrome", {"browserName":"chrome","chromeOptions":{"w3c":false,"args":["--disable-gpu","--headless", "--no-sandbox", "--disable-dev-shm-usage"]}}, "http://selenium-chrome:4444/wd/hub"]
      BROWSERTEST_OUTPUT_DIRECTORY: /var/www/html/web/sites/simpletest/browser_output
      BROWSERTEST_OUTPUT_BASE_URL: ${DDEV_PRIMARY_URL}
      # Nightwatch
      DRUPAL_TEST_BASE_URL: *base_url
      DRUPAL_TEST_DB_URL: *simpletest_db_sqlite
      DRUPAL_TEST_WEBDRIVER_HOSTNAME: selenium-chrome
      DRUPAL_TEST_WEBDRIVER_PORT: 4444
      DRUPAL_TEST_WEBDRIVER_PATH_PREFIX: /wd/hub
      DRUPAL_TEST_CHROMEDRIVER_AUTOSTART: false
      DRUPAL_NIGHTWATCH_SEARCH_DIRECTORY: ../
      DRUPAL_NIGHTWATCH_IGNORE_DIRECTORIES: node_modules,vendor,.*,sites/*/files,sites/*/private,sites/simpletest
      DRUPAL_NIGHTWATCH_OUTPUT: reports/nightwatch
      DTT_BASE_URL: *base_url
      DTT_MINK_DRIVER_ARGS: *mink_driver_args
